name: prose_1to1

# shared attributes
dim_emb: 1024
dim_ffn: 2048
dropout: 0
attn_dropout: 0
n_head: 8
norm_first: true
qk_norm: 0
norm: rms # select from [layer, rms]
activation: gelu
rotary: 0
flex_attn: 0

patch_num: 8 # for input, number of patches per dimension
patch_num_output: 16 # for output, number of patches per dimension

time_embed: learnable # select from continuous and learnable

embedder:
    # choose from [linear, conv, overlap_linear, fno, fourier] 
    type: conv
    dim: ${..dim_emb}
    patch_num: ${..patch_num}
    patch_num_output: ${..patch_num_output}

    time_embed: ${..time_embed}

    initialize_small_output: 0
    
    conv_dim: 32
    early_conv: 0

    deep: 0


data_encoder:
    n_layer: 7
    positional_embedding: null

    dim_emb: ${..dim_emb}
    dim_ffn: ${..dim_ffn}
    n_head: ${..n_head}
    dropout: ${..dropout}
    attn_dropout: ${..attn_dropout}
    norm_first: ${..norm_first}
    qk_norm: ${..qk_norm}
    norm: ${..norm}
    activation: ${..activation}
    rotary: ${..rotary}
    flex_attn: ${..flex_attn}


data_decoder:
    n_layer: 12
    query_dim: 1 # time: 1, space: 2
    self_attn: 0 # 0: disable, 1: restricted self_attn, 2: full self_attn
    time_embed: ${..time_embed}
    patch_num_output: ${..patch_num_output}
    final_ln: 1 # whether to have final norm layer

    dim_emb: ${..dim_emb}
    dim_ffn: ${..dim_ffn}
    n_head: ${..n_head}
    dropout: ${..dropout}
    attn_dropout: ${..attn_dropout}
    norm_first: ${..norm_first}
    qk_norm: ${..qk_norm}
    norm: ${..norm}
    activation: ${..activation}
    rotary: ${..rotary}
    flex_attn: ${..flex_attn}